import type { LevelDef } from './LevelBuilder';

/**
 * The six shifts of COLD STORAGE, from orientation to the vault.
 * All geometry is authored on the XZ plane; perimeter walls, ceiling,
 * fixtures, and windows are generated by the LevelBuilder.
 */
export const LEVELS: LevelDef[] = [
  // ------------------------------------------------------------------
  // L0 — ORIENTATION DAY (tutorial)
  // ------------------------------------------------------------------
  {
    id: 'orientation',
    name: 'ORIENTATION DAY',
    floorLabel: 'FLOOR 2 · ONBOARDING',
    briefing: {
      from: 'PAL — People & Alignment Liaison (automated)',
      lines: [
        'Welcome to Halcyon Dynamics, Employee #7431.',
        'Today: locate your desk, complete mobility compliance, and enjoy the lunch you brought from home.',
        'Halcyon reminds you that the communal refrigerator operates on the honor system.',
        'The honor system has a 4% success rate.'
      ]
    },
    palette: {
      wall: 0x8f95a1, accent: 0x7dd3fc,
      carpetA: '#4d525d', carpetB: '#505560', fog: 0x11141a
    },
    size: [26, 18],
    spawn: { x: -10, z: 6, yaw: -0.9 },
    walls: [
      [-9.5, 0, 7, 0.4],
      [1, 0, 10, 0.4],
      [10.5, 0, 5, 0.4]
    ],
    desks: [[-8, -4], [-4, -4], [0, -4], [4, -4]],
    props: [
      { type: 'copier', x: -11, z: -4 },
      { type: 'plant', x: 12, z: 4 },
      { type: 'cooler', x: 11, z: 6 },
      { type: 'table', x: 8, z: -6.5 },
      { type: 'plant', x: -12, z: 7 }
    ],
    doors: [{ hinge: [-6, 0], length: 2, axis: 'x' }],
    keycards: [],
    guards: [],
    notes: [
      { x: 0, z: -3.6, text: 'PAL ONBOARDING CARD — "Your desk is your castle. Your chair is your throne. Your lunch is, statistically, someone else\'s."' },
      { x: 8.2, z: -6.1, y: 0.82, text: 'BREAKROOM POSTER — "FRIDGE CRIME: A JOURNEY. Talk to HR today!" Someone has drawn a tiny crown on the sandwich.' }
    ],
    lights: [[-6, -4], [6, -4], [-6, 4], [6, 4]],
    windowsSide: 'S',
    fridge: { x: 11.8, z: -7.2 },
    exit: { x: -10, z: 6, r: 1.5 },
    objectives: {
      start: 'Report to your assigned desk.',
      toFridge: 'End of day. Retrieve YOUR lunch from the breakroom fridge.',
      escape: ''
    },
    tutorial: true,
    lunchName: 'YOUR LUNCH'
  },

  // ------------------------------------------------------------------
  // L1 — THE BULLPEN
  // ------------------------------------------------------------------
  {
    id: 'bullpen',
    name: 'THE BULLPEN',
    floorLabel: 'FLOOR 3 · GENERAL OPERATIONS',
    briefing: {
      from: 'A note, folded into your keyboard. Unsigned. Smells faintly of floor wax.',
      lines: [
        '"They took yours on day one. That was not an accident. Nothing here is."',
        '"The intern, Dorian, keeps a lunch in the Floor 3 breakroom. Take it, and the building will notice you."',
        '"Blue keycard. Someone always leaves it on a desk. People are careless before they are executives."',
        '— M.'
      ]
    },
    palette: {
      wall: 0x8f95a1, accent: 0x7dd3fc,
      carpetA: '#4d525d', carpetB: '#505560', fog: 0x11141a
    },
    size: [40, 24],
    spawn: { x: -17, z: 8, yaw: -0.56 },
    walls: [
      [10, -9.2, 0.4, 5.6],
      [10, 3.8, 0.4, 16.4],
      [-16.5, 0, 7, 0.4],
      [-7.5, 0, 7, 0.4]
    ],
    partitions: [
      [-8, -6, 10, 0.15],
      [-8, -2.2, 10, 0.15],
      [0.4, -6, 0.15, 4],
      [4, 4.8, 6, 0.15]
    ],
    columns: [[4, 0], [4, -8], [-2, 6]],
    desks: [
      [-14, -8], [-10, -8], [-6, -8], [-2, -8],
      [-14, -4], [-10, -4], [-6, -4], [-2, -4],
      [-14, 6], [-10, 6], [-6, 6],
      [2, 4], [6, 4]
    ],
    props: [
      { type: 'table', x: 14, z: -8 },
      { type: 'counter', x: 13, z: 2 },
      { type: 'crate', x: 16.5, z: 8.5 },
      { type: 'crate', x: 18, z: 8.5 },
      { type: 'plant', x: -18.5, z: -8.5 },
      { type: 'plant', x: 18.5, z: 10.5 },
      { type: 'cooler', x: 12, z: 8 },
      { type: 'copier', x: -18, z: -10 }
    ],
    doors: [{ hinge: [10, -6.4], length: 2, axis: 'z', locked: 'BLUE' }],
    keycards: [{ id: 'BLUE', x: -2, z: -3.72, color: 0x3b82f6 }],
    guards: [
      { name: 'Officer Dwight', waypoints: [[-12, -10.5], [8, -10.5], [8, 8.5], [-12, 8.5]] },
      { name: 'Officer Pat', waypoints: [[12, -10.8], [17, -10.8], [17, -5.5], [12, -5.5]], viewDist: 12 },
      { name: 'Gary (Accounts)', waypoints: [[-15.5, 8.5], [-4.5, 8.5], [-4.5, 4.5], [-15.5, 4.5]], civilian: true, patrolSpeed: 1.3 }
    ],
    notes: [
      { x: 13.4, z: 1.2, y: 0.95, text: 'ALL-STAFF MEMO #1 (B. Kowalczyk, Security) — "A lunch was reported MISSING on Floor 2. This is now a Category C incident. I have requested a second lanyard."' },
      { x: -6, z: -3.6, text: 'STICKY NOTE (Gary) — "IOU one (1) yogurt. The market conditions demanded it. — G"' },
      { x: -17.5, z: 9.5, y: 0.03, text: 'FOLDED NOTE — "Cameras arrive on Floor 7. Walk like you have a meeting. Nobody stops a person with a meeting." — M.' }
    ],
    restricted: [[15, -6, 10, 12]],
    lights: [[-10, -6], [-10, 6], [0, 0], [15, -6]],
    windowsSide: 'S',
    fridge: { x: 19.3, z: -10 },
    exit: { x: -18.3, z: 8, r: 1.6 },
    objectives: {
      start: "Dorian's lunch is in the breakroom fridge. Find the BLUE keycard.",
      toFridge: 'Get into the breakroom. The fridge hums like it knows.',
      escape: 'Return to the elevator. Walk like you belong.'
    },
    lunchName: "DORIAN'S LUNCH"
  },

  // ------------------------------------------------------------------
  // L2 — MIDDLE MANAGEMENT
  // ------------------------------------------------------------------
  {
    id: 'management',
    name: 'MIDDLE MANAGEMENT',
    floorLabel: 'FLOOR 7 · STRATEGIC ALIGNMENT',
    briefing: {
      from: 'Marv (Custodial) — whispered by the mop closet',
      lines: [
        '"Promoted after one day. You feel that? That\'s the Program noticing you."',
        '"Floor 7 has cameras now. Green light means bored. Red light means paperwork — for you."',
        '"Dorian eats in the manager wing these days. Yellow clearance. The receptionist keeps hers by the phone."',
        '"One more thing: the lid of that container you took. Look at the engraving. They all have one."'
      ]
    },
    palette: {
      wall: 0xa39a88, accent: 0xffc53d,
      carpetA: '#565049', carpetB: '#5a544c', fog: 0x14120e, sun: 0xffd9a0
    },
    size: [40, 24],
    spawn: { x: -17, z: 9, yaw: -0.9 },
    walls: [
      [-11, 6, 18, 0.4],
      [7, 6, 14, 0.4],
      [18, 6, 4, 0.4],
      [10, -7, 0.4, 10],
      [10, 3, 0.4, 6]
    ],
    partitions: [
      [-8, -4.5, 12, 0.15],
      [-8, 0.5, 12, 0.15]
    ],
    columns: [[3, -4], [3, 2]],
    desks: [
      [-14, -7], [-10, -7], [-6, -7], [-2, -7],
      [-14, -2], [-10, -2], [-6, -2], [-2, -2],
      [-14, 3], [-10, 3],
      [5, 8.5],
      [13.5, -8]
    ],
    props: [
      { type: 'plant', x: -18.5, z: 4.5 },
      { type: 'plant', x: 1.2, z: 7.5 },
      { type: 'cooler', x: -18.9, z: -3 },
      { type: 'copier', x: -4, z: -10.8 },
      { type: 'table', x: 15, z: -5 },
      { type: 'shelf', x: 19.3, z: -4 },
      { type: 'plant', x: 18.8, z: 4.8 }
    ],
    doors: [
      { hinge: [-2, 6], length: 2, axis: 'x' },
      { hinge: [10, -2], length: 2, axis: 'z', locked: 'YELLOW' }
    ],
    keycards: [{ id: 'YELLOW', x: 5, z: 8.1, color: 0xeab308 }],
    guards: [
      { name: 'Officer Chen', waypoints: [[-16, -10.5], [6, -10.5], [6, 4.6], [-16, 4.6]] },
      { name: 'Officer Okafor', waypoints: [[12, -10.8], [17.5, -10.8], [17.5, -3], [12, -3]], viewDist: 13 },
      { name: 'Deb (Ops)', waypoints: [[-16, 9.5], [3, 9.5], [3, 7.2], [-16, 7.2]], civilian: true, patrolSpeed: 1.4 }
    ],
    cameras: [
      { x: -1, z: 5.3, facing: Math.PI, arc: 0.5, range: 9 },
      { x: 9.6, z: -1, facing: Math.PI / 2, arc: 0.55, range: 10 }
    ],
    notes: [
      { x: 4.6, z: 8.9, y: 0.95, text: 'PROMOTION MEMO — "Effective immediately: #7431, Junior Associate → Associate. Justification: [REDACTED]. Welcome to Floor 7. — A.H."' },
      { x: 19, z: -3.7, y: 1.15, text: 'ALL-STAFF MEMO #4 (B. Kowalczyk) — "The Floor 3 incident was NOT the HVAC. I have moved the security budget request to FONT SIZE 16."' },
      { x: -10, z: -1.6, text: 'CHAT PRINTOUT — "…okay but WHY does the new intern have a BETTER lunch on every floor?? like an identical, better lunch??" — deleted by moderator' }
    ],
    restricted: [[15, -3, 10, 18]],
    lights: [[-10, -5], [0, -5], [-10, 2], [14, -6], [0, 9], [-14, 9]],
    windowsSide: 'S',
    fridge: { x: 18.7, z: -10 },
    exit: { x: -18.3, z: 9, r: 1.6 },
    objectives: {
      start: 'The YELLOW keycard is at reception. The manager wing is watching.',
      toFridge: 'Enter the manager wing. Mind the cameras.',
      escape: 'Back to the elevator. You have a meeting. You have always had a meeting.'
    },
    lunchName: "DORIAN'S LUNCH (DELUXE)"
  },

  // ------------------------------------------------------------------
  // L3 — THE GLASS FLOOR
  // ------------------------------------------------------------------
  {
    id: 'glass',
    name: 'THE GLASS FLOOR',
    floorLabel: 'FLOOR 12 · EXECUTIVE OPERATIONS',
    briefing: {
      from: 'Marv — via a note taped inside your new office chair',
      lines: [
        '"Floor 12. Everything is glass. Transparency, they call it. Means everyone sees everything, always."',
        '"The assistants are worse than security. They walk fast and they remember faces."',
        '"Green clearance for the executive lounge. There\'s a card in the northwest office — the exec who owned it got \'aligned\' last quarter."',
        '"Second lid says 8. First said 1. Keep them. — M."'
      ]
    },
    palette: {
      wall: 0x8a7462, accent: 0xd8a05a,
      carpetA: '#4a3f38', carpetB: '#4e433b', fog: 0x120f0c,
      sun: 0xffcf9a, hemiSky: 0xe8d9c8
    },
    size: [40, 24],
    spawn: { x: -17, z: 8, yaw: -0.9 },
    walls: [],
    glass: [
      [-13, -2, 14, 0.3],
      [1, -2, 10, 0.3],
      [-12, -8.5, 0.3, 7],
      [-4, -8.5, 0.3, 7],
      [4, -8.5, 0.3, 7],
      [12, 0, 0.3, 4],
      [12, 8, 0.3, 8]
    ],
    desks: [
      [-16, -8], [-8, -8], [0, -8], [8, -8],
      [-10, 6], [-6, 6], [-2, 6], [-10, 10], [-6, 10]
    ],
    props: [
      { type: 'plant', x: -19, z: -3 },
      { type: 'plant', x: 11, z: 11 },
      { type: 'plant', x: 13, z: -1 },
      { type: 'table', x: 15.5, z: 4.5 },
      { type: 'cooler', x: -19, z: 11 },
      { type: 'copier', x: 2, z: 11 }
    ],
    doors: [
      { hinge: [-6, -2], length: 2, axis: 'x' },
      { hinge: [12, 2], length: 2, axis: 'z', locked: 'GREEN' }
    ],
    keycards: [{ id: 'GREEN', x: -8, z: -7.6, color: 0x34d399 }],
    guards: [
      { name: 'Officer Sloane', waypoints: [[-17, 0], [10, 0]], viewDist: 13 },
      { name: 'Asst. Mercer', waypoints: [[-16, -3.5], [8, -3.5]], civilian: true, patrolSpeed: 2.0, viewDist: 14 },
      { name: 'Asst. Vale', waypoints: [[14, 0], [17.6, 0], [17.6, 10], [14, 10]], civilian: true, patrolSpeed: 1.8, viewDist: 13 }
    ],
    cameras: [
      { x: -14, z: 1.7, facing: 0, arc: 0.6, range: 11 },
      { x: 8, z: -1.7, facing: Math.PI, arc: 0.6, range: 10 }
    ],
    notes: [
      { x: -16, z: -7.6, text: 'PERFORMANCE REVIEW (final page) — "Employee exhibits insufficient hunger. Literally. Brings no lunch. Recommend: alignment." The name is blacked out.' },
      { x: 13, z: 9, y: 0.03, text: 'ALL-STAFF MEMO #9 (B. Kowalczyk) — "To whoever keeps taking the lunches: the cameras are ON now. I picked the ones with the little red light MYSELF."' },
      { x: -6, z: 6.4, text: 'STICKY NOTE — "Dorian was in the lounge again. Nobody hired him for Floor 12. Nobody remembers hiring him at all." ' }
    ],
    restricted: [[16, 5, 8, 14]],
    lights: [[-14, 0], [-2, 0], [8, -8], [-10, 7], [16, 4], [16, -6]],
    windowsSide: 'N',
    fridge: { x: 18.7, z: 7 },
    exit: { x: -18.3, z: 8, r: 1.6 },
    objectives: {
      start: 'GREEN clearance is in the northwest office. Glass remembers nothing. Assistants remember everything.',
      toFridge: 'The executive lounge fridge. Through the glass, past the assistants.',
      escape: 'Elevator. Do not run. Running is a confession.'
    },
    lunchName: "DORIAN'S LUNCH (ARTISANAL)"
  },

  // ------------------------------------------------------------------
  // L4 — R&D
  // ------------------------------------------------------------------
  {
    id: 'rnd',
    name: 'RESEARCH & DEVELOPMENT',
    floorLabel: 'FLOOR 21 · APPLIED CULINARY SCIENCE',
    briefing: {
      from: 'Marv — spoken openly this time, mop abandoned',
      lines: [
        '"Floor 21 is where they make it. The lunch. The one Dorian carries. It\'s the company\'s only real product."',
        '"Lasers at knee height. The techs wear headphones — deaf as drywall, eyes like hawks."',
        '"Cyan card in cold storage annex, northwest room. The specimen fridge is in the middle of the lab."',
        '"Third lid: 7. You\'re collecting a number, Associate. Sub-Level B has a door that wants it. — M."'
      ]
    },
    palette: {
      wall: 0xc5cdd4, accent: 0x22d3ee,
      carpetA: '#5d666d', carpetB: '#616a71', fog: 0x0e1216,
      sun: 0xeaf4ff, sunIntensity: 2.2, hemiSky: 0xdfeef8
    },
    size: [40, 24],
    spawn: { x: -17, z: 9, yaw: -0.9 },
    walls: [
      [-4.5, -6, 7, 0.4],
      [4.5, -6, 7, 0.4],
      [-4.5, 2, 7, 0.4],
      [4.5, 2, 7, 0.4],
      [-8, -2, 0.4, 8],
      [8, -2, 0.4, 8],
      [-19, -5, 2, 0.4],
      [-15, -5, 2, 0.4],
      [-14, -8.5, 0.4, 7]
    ],
    desks: [
      [-4, -10.8], [4, -10.8],
      [-4.5, -2.5], [4.5, -2.5],
      [-10, 8], [-6, 8], [-2, 8], [2, 8]
    ],
    props: [
      { type: 'shelf', x: -16, z: -10.8 },
      { type: 'shelf', x: -18.5, z: -10.8 },
      { type: 'copier', x: -16, z: 8 },
      { type: 'plant', x: 19, z: 10.8 },
      { type: 'crate', x: 12, z: 10.8 },
      { type: 'cooler', x: -19, z: 2.6 }
    ],
    doors: [
      { hinge: [-18, -5], length: 2, axis: 'x' },
      { hinge: [-1, 2], length: 2, axis: 'x', locked: 'CYAN' }
    ],
    keycards: [{ id: 'CYAN', x: -16, z: -10.3, y: 1.15, color: 0x22d3ee }],
    guards: [
      { name: 'Tech Ruiz', waypoints: [[-6, -9.3], [6, -9.3]], civilian: true, deaf: true, viewDist: 15, shirt: 0xd8dde2, pants: 0x9aa2ab },
      { name: 'Tech Imani', waypoints: [[-6, 4], [6, 4]], civilian: true, deaf: true, viewDist: 15, shirt: 0xd8dde2, pants: 0x9aa2ab },
      { name: 'Officer Novak', waypoints: [[17.5, -10.5], [17.5, 10.5], [-11.5, 10.5], [11, 4.5]], viewDist: 13, patrolSpeed: 1.9 }
    ],
    cameras: [
      { x: 0, z: -5.5, facing: Math.PI, arc: 0.35, range: 8 }
    ],
    lasers: [
      { x0: 8.4, z0: -8, x1: 16, z1: -8 },
      { x0: 12, z0: -3, x1: 19.8, z1: -3 },
      { x0: 8.4, z0: 2, x1: 16, z1: 2 },
      { x0: -19.8, z0: 1, x1: -13, z1: 1 },
      { x0: -9, z0: 6, x1: -2, z1: 6 }
    ],
    notes: [
      { x: -16.6, z: -9.5, y: 1.15, text: 'SHIPMENT MANIFEST — "Batch 88: 1 (one) lunch. Destination: wherever the current intern is. Recipe source: DO NOT ASK (1987)."' },
      { x: 4.5, z: -2.1, y: 0.95, text: 'SPECIMEN LOG — "Day 40: the sandwich has not aged. Morale team wept again. Dorian collected it at noon, as always. Who signs Dorian\'s badge??"' },
      { x: -6, z: 8.4, text: 'STICKY NOTE (on a headphone case) — "If you see someone crouching in here it is NOT a wellness exercise. Page Brenda."' }
    ],
    restricted: [[0, -2, 16, 8], [-17, -8.5, 6, 7]],
    lights: [[-6, -9], [0, -2], [6, 4], [14, -3], [-16, -8], [-6, 8]],
    windowsSide: 'N',
    fridge: { x: 0, z: -2.5 },
    exit: { x: -18.3, z: 9, r: 1.6 },
    objectives: {
      start: 'CYAN clearance sits in the cold annex, northwest. The lab is a restricted zone.',
      toFridge: 'The specimen fridge, center lab. The camera never blinks. The techs never hear.',
      escape: 'Elevator. Step OVER nothing — the lasers are at knee height for a reason.'
    },
    lunchName: 'SPECIMEN 88 (A LUNCH)'
  },

  // ------------------------------------------------------------------
  // L5 — COLD STORAGE (finale)
  // ------------------------------------------------------------------
  {
    id: 'vault',
    name: 'COLD STORAGE',
    floorLabel: 'SUB-LEVEL B · UNLISTED',
    briefing: {
      from: 'Marv — waiting for you inside the service elevator',
      lines: [
        '"Lids: 1, 8, 7. And the year the founder walked into this building with a lunch his mother made him: 1987."',
        '"He never ate it. Success came that day, and he decided the hunger was the secret. The First Lunch went into the vault. The Program went into the handbook."',
        '"Every floor is restricted down here. Every camera is angry. The black card is on the security desk, northeast."',
        '"Whatever you find in that fridge — you\'ll know what to do. Or you won\'t. Both are answers. — M."'
      ]
    },
    palette: {
      wall: 0x3d4a5f, accent: 0x7dd3fc,
      carpetA: '#2e3644', carpetB: '#313a49', fog: 0x0a0e16,
      sun: 0x9fc3e8, sunIntensity: 1.5, hemiSky: 0x8fb3d8, hemiGround: 0x1a2230
    },
    size: [44, 26],
    spawn: { x: -20, z: 11, yaw: -0.8 },
    walls: [
      [0, -8, 12, 0.4],
      [-3.5, 2, 5, 0.4],
      [3.5, 2, 5, 0.4],
      [-6, -3, 0.4, 10],
      [6, -3, 0.4, 10]
    ],
    desks: [[15, -9]],
    props: [
      { type: 'crate', x: 0, z: 11.5 },
      { type: 'crate', x: 4, z: 11.5 },
      { type: 'crate', x: -4, z: 11.5 },
      { type: 'shelf', x: 21, z: -8 },
      { type: 'shelf', x: 21, z: -4 },
      { type: 'shelf', x: 21, z: 0 },
      { type: 'crate', x: -21, z: -11.5 },
      { type: 'crate', x: -21, z: -9.8 }
    ],
    doors: [{ hinge: [-1, 2], length: 2, axis: 'x', locked: 'BLACK' }],
    keycards: [{ id: 'BLACK', x: 15, z: -8.6, color: 0x64748b }],
    guards: [
      { name: 'Warden Kowalczyk', waypoints: [[-8, 4], [8, 4], [8, -10], [-8, -10]], viewDist: 15, patrolSpeed: 2.2, shirt: 0x1c2733, pants: 0x11161f },
      { name: 'Spectre East', waypoints: [[11, -11], [19.5, -11], [19.5, 11], [11, 11]], viewDist: 15, patrolSpeed: 2.2, shirt: 0x1c2733, pants: 0x11161f },
      { name: 'Spectre West', waypoints: [[-11, -11], [-19.5, -11], [-19.5, 11], [-11, 11]], viewDist: 15, patrolSpeed: 2.2, shirt: 0x1c2733, pants: 0x11161f },
      { name: 'Rover Six', waypoints: [[-15, 9], [15, 9]], viewDist: 14, patrolSpeed: 2.4, shirt: 0x1c2733, pants: 0x11161f }
    ],
    cameras: [
      { x: 0, z: 3.5, facing: Math.PI, arc: 0.6, range: 11 },
      { x: -12, z: -12.3, facing: Math.PI, arc: 0.7, range: 10 },
      { x: 12, z: -12.3, facing: Math.PI, arc: 0.7, range: 10 },
      { x: 0, z: 12.3, facing: 0, arc: 0.7, range: 10 }
    ],
    lasers: [
      { x0: -21.8, z0: -6, x1: -12, z1: -6 },
      { x0: -14, z0: -1, x1: -6.4, z1: -1 },
      { x0: -21.8, z0: 5, x1: -12, z1: 5 },
      { x0: 12, z0: -6, x1: 21.8, z1: -6 },
      { x0: 6.4, z0: -1, x1: 14, z1: -1 },
      { x0: 12, z0: 5, x1: 21.8, z1: 5 }
    ],
    notes: [
      { x: 14.6, z: -9.4, y: 0.95, text: 'FINAL MEMO (B. Kowalczyk) — "Request DENIED for the 40th year: \'additional lock for the old fridge.\' Justification given: \'the hunger must remain possible.\' Signed A.H. I quit. Effective the moment someone reads this."' },
      { x: 0.7, z: -4.3, y: 0.03, text: 'HANDWRITTEN, 1987 — "If you are reading this, you got past everything I built to stop you. So it\'s yours now. All of it. The company, the hunger, the sandwich. Choose better than I did. — Aldous"' }
    ],
    restricted: [[0, 0, 44, 26]],
    lights: [[-11, -6], [11, -6], [0, 5], [0, -11], [-11, 7], [11, 7]],
    windowsSide: null,
    fridge: { x: 0, z: -3.5 },
    exit: { x: -20.3, z: 11, r: 1.6 },
    exitLockdown: { x: 20.3, z: -11.5, r: 1.8 },
    objectives: {
      start: 'The BLACK card is on the security desk. Everything down here is trespassing. Everything.',
      toFridge: 'The vault door. Behind it: the First Lunch, 1987, never eaten.',
      escape: 'LOCKDOWN. The service elevator is sealed — the freight elevator, northeast corner. RUN or GHOST, your call.'
    },
    finale: true,
    lunchName: 'THE FIRST LUNCH (1987)'
  }
];

export const ENDING_CEO = {
  title: 'THE CORNER OFFICE',
  body:
    'You carry the First Lunch to the surface, still wrapped, still perfect, still uneaten. ' +
    'By morning there is a memo with your name on it and a title nobody remembers creating: Chief Executive. ' +
    'Marv — Aldous — hands you the building with a nod and finally, after thirty-nine years, goes home. ' +
    'On your first day you install a lock on every fridge in the building. On your second day, you understand the founder completely: ' +
    'you are hungry, you are powerful, and you will never, ever eat.'
};

export const ENDING_LUNCH = {
  title: 'LUNCH BREAK',
  body:
    'You sit down on the vault floor, cross-legged under four furious cameras, and you eat the First Lunch. ' +
    'It is a sandwich. It is a very good sandwich. Somewhere upstairs, an alarm gives up. ' +
    'The Program ends the way all corporate mysticism ends: quietly, at lunch. ' +
    'Dorian finds you there, sits down, and splits his own lunch with you — the first one he has ever shared. ' +
    '"Finally," the intern says. "Someone who gets it." You are unemployed by Monday. You are free forever.'
};
